- package.json
- yarn.lock
Updating to the latest version of the mongo driver.
> Update mongo driver.

- src/schema/index.js
- src/schema/resolvers.js
- test/queries.test.js
This is the minimum viable query for an individual account details.
> Add basic query by account id

- .circleci/config.yml
- package.json
Running most node.js tests in CircleCI
@evadb for review
/cc @sleepycat
> initial circleci config

- README.md
> add circleci status badge to readme

- .circleci/config.yml
> lint in CircleCI

- README.md
This list didn't get updated with the rest of the examples.
> Update list of env vars in readme

- .circleci/config.yml
- python/pylintrc
Please forgive the excess length of this PR, it's mostly a default `pylintrc` file with some sane defaults.
/cc @evadb @sleepycat
> better tests, add linting and type checking

- .circleci/config.yml
- python/requirements.txt
- python/src/energuide/database.py
- python/tests/conftest.py
- python/tests/sample.csv
- python/tests/test_database.py
> Mongo insert

- .gitignore
- python/tests/test_basic.py
Couple very small edits:
- adds some python artifacts to the `.gitignore` file
- deletes the "do-nothing" test file that was just exercising CI, now that we actually have tests
> some small maintenance tasks

- python/src/energuide/database.py
- python/tests/conftest.py
Improved connection string logic so we can make some module functions private. No longer needed by the test logic.
> hide connection string creator

- python/src/energuide/dwelling.py
- python/tests/test_dwelling.py
Adds the first member of `Dwelling` that requires its own class, `Evaluation`.  I also started namespacing the tests in `test_dwelling` for clarity.
> add Evaluation class

- python/requirements.txt
- python/src/energuide/dwelling.py
Uses a package called `cerberus` for validating the dict values that are passed into `Evaluation.from_data` and `Dwelling.from_data`
> nicer schema validation

- python/src/energuide/dwelling.py
- python/tests/test_dwelling.py
This PR adds the entry_date, creation_date, and modification_date to the `Evaluation` class.
> adding entry_date, creation_date, and modification_date

- python/src/energuide/dwelling.py
- python/tests/test_dwelling.py
Based on some offline feedback, I've separated out the input data schema verification and parsing from the Dwelling/Evaluation hierarchy construction.
> parse data rows before creating structure

- python/src/energuide/interpreter.py
- python/src/energuide/reader.py
- python/tests/test_interpreter.py
- python/tests/test_reader.py
Some light refactoring, pulling reader functionality out of interpreter.
> separate and refactor reading functionality

- python/src/energuide/reader.py
> simplify grouping logic

- src/schema/index.js
Added to both the enum type and the return type
> Add description to yearBuilt

- python/src/energuide/database.py
- python/src/energuide/dwelling.py
- python/tests/test_database.py
- python/tests/test_dwelling.py
One of the last pieces to our refactored data pipeline - the 'grouped load' function. In a following PR, this code will be used in a revised `transform.run` function (or similar).
> add new grouped_load command

- python/README.md
We will need to begin integrating ETL output and API input assumptions very soon. To that end, I've updated the README to make installation instructions more detailed for everyone's benefit.
> update python readme with more detailed instructions

- python/src/energuide/extractor.py
- python/tests/test_extractor.py
Adds a write_data method to the extractor. The CLI will call the `extract_data` method to pull the data from the raw input file, and the `write_data` method to write the extracted and validated data to an output file.
> add a write_data method to extractor

- python/src/energuide/cli.py
- python/tests/test_cli.py
Add function to CLI that uses the new extract_data and write_data functions.
> Extract cli

- python/src/energuide/extractor.py
Splitting up the `validate` function so the validation, data extraction, and PII key removals all occur in distinct private functions. This will give us a more logical place to put additional XML parsing functions.
> split up validator into multiple individual functions

- python/src/energuide/extractor.py
- python/tests/test_cli.py
- python/tests/test_extractor.py
Change the `write_data` function of extractor to output a zip of json files instead of outputting one json file with many blobs
> Refactor extractor to output a zip file

- src/schema/types/Latitude.js
- test/Latitude.test.js
This transplant from a previous project never had proper tests. Refactoring to give it proper parseValue and parseLiteral functions and testing all the things.
> Refactor and test Latitude type

- python/requirements.txt
- python/src/energuide/extractor.py
- python/src/energuide/snippets.py
- python/tests/test_extractor.py
- python/tests/test_snippets.py
This is a repeat of #61, which I accidentally merged into the wrong branch.
> Split up validator

- python/tests/test_extractor.py
This approach looks much easier on the eyes, and is easier to debug. Same effect.
> refactoring extractor tests for readability

- python/src/energuide/extractor.py
- python/tests/conftest.py
- python/tests/test_cli.py
- python/tests/test_extractor.py
Adding fields INFO1-INFO10 to the list of required dropped fieds. 
While these fields do not necessarily contain PII, from observation it seems some data entry personnel sometimes enter their names in some of these fields.
> Clean data

- python/src/energuide/extractor.py
- python/src/energuide/reader.py
- python/src/energuide/transform.py
- python/tests/test_reader.py
remove unsed read function of reader, and rename zip_read to read. Remove unused _SerializableGenerator
> Removed unused code

- python/src/energuide/dwelling.py
- python/tests/test_dwelling.py
This pull request adds logic to dwelling.py to load the floor data into mongodb
> add load logic for floors

- python/src/energuide/dwelling.py
- python/src/energuide/extracted_datatypes.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
This pull request is to refactor dwelling to move datatypes for xml extracted data to extracted_datatypes.py
While it may seem like a large pull request, the vast majority is simply copy/paste
> Refactor dwelling.py

- python/src/energuide/extractor.py
- python/src/energuide/snippets.py
- python/tests/test_snippets.py
This PR adds the new `code` section to the extracted data, providing necessary context for the upcoming `wall` extraction.
> adding code extractor

- python/pylintrc
- python/src/energuide/snippets.py
- python/tests/test_snippets.py
Duplicate of #75. I forgot to change the base branch again.
FYI @buckley-w-david
> extract wall details

- test/server.test.js
> Refactor server test

- test/PostalCode.test.js
Prettier doesn't format inside template literals.
> Cleaning up formatting

- src/schema/types/Longitude.js
- test/Longitude.test.js
This type was brought over from a previous project and needed a little love to bring it up to scratch.
> Add tests for and refactor Longitude type

- python/src/energuide/dwelling.py
- python/src/energuide/extracted_datatypes.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
Factoring out the `WallCode` and `Codes`(which will eventually have more than just wall codes) classes from #79
> add code parsing

- README.md
Removing SQL reference and updating collection names and queries.
> Update readme to reflect current state.

- python/src/energuide/snippets.py
- python/tests/test_snippets.py
This PR adds extraction of the raw window data. Windows are always embedded within a wall, door, ceiling, or basement element.
https://trello.com/c/edPnfM4G/125-extract-load-window-data
> Extract window

- python/src/energuide/dwelling.py
- python/src/energuide/extracted_datatypes.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
Transform & load doors into the database. Differing slightly from the HOIS at this point, which aggregates door information somewhat, while this leaves each door as a separate data point. Taking the same approach with Windows.
> transform and load doors

- python/src/energuide/extracted_datatypes.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
This PR adds parsing of window code data into `WindowCode` objects.
https://trello.com/c/edPnfM4G/125-extract-load-window-data
> Parse window codes

- python/src/energuide/extracted_datatypes.py
- python/src/energuide/snippets.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
- python/tests/test_snippets.py
As we discussed IRL, also extracting and loading door labels.
> also extract and load door labels

- api/test/queries.test.js
> Move repeated server init code to beforeAll

- api/src/schema/resolvers.js
- api/test/queries.test.js
Now that filters are added, these are some integration tests to make sure the whole thing is all tied together nicely.
> Add integration tests for filters

- python/src/energuide/dwelling.py
- python/src/energuide/extracted_datatypes.py
- python/src/energuide/snippets.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
- python/tests/test_snippets.py
Transform & load windows into the database
Also makes a minor fix to `glazingTypes` fields in Window code
https://trello.com/c/edPnfM4G/125-extract-load-window-data
> Load window

- python/src/energuide/snippets.py
- python/tests/test_snippets.py
This PR adds functionality to extract the above and below grade heated floor area data.
https://trello.com/c/q0fW8AUX/112-extract-load-heated-floor-data
> extract heated floor area data

- python/src/energuide/dwelling.py
- python/src/energuide/extracted_datatypes.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
- python/tests/test_snippets.py
This PR adds functionality to transform and load extracted heated floor area data.
https://trello.com/c/q0fW8AUX/112-extract-load-heated-floor-data
> load heated floor area data

- api/src/schema/__tests__/schema.test.js
- api/src/schema/index.js
This commit adds Door, Wall, Ceiling and Window types to the schema.
> Add new types to schema

- python/tests/test_snippets.py
This PR adds a missing test that should have been added in #111 
https://trello.com/c/Wqamkah5/136-refactor-snippets
> add missing HouseSnippet.to_dict() test

- python/src/energuide/snippets.py
- python/tests/sample.h2k
- python/tests/test_snippets.py
This PR extracts the raw `ventilation` xml from the source. This will be parsed and interpreted in the transform layer.
> Extract raw ventilation xml

- .circleci/config.yml
- python/mypy.ini
- python/setup.py
- python/src/energuide/dwelling.py
- python/src/energuide/element.py
- python/src/energuide/extracted_datatypes.py
- python/src/energuide/snippets.py
- python/src/energuide/validator.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
- python/tests/test_extractor.py
- python/tests/test_snippets.py
- python/tests/test_validator.py
This PR moves some Transform logic out of the extractor, and puts it in the Transform layer for the `ceilings` type.
> Extract only raw xml ceilings snippets

- python/src/energuide/snippets.py
- python/tests/sample.h2k
- python/tests/test_snippets.py
Duplicate of #114. I forgot to change the base branch
FYI @JasonMWhite
> Extract ventilation

- python/src/energuide/dwelling.py
- python/src/energuide/extracted_datatypes.py
- python/src/energuide/snippets.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
- python/tests/test_snippets.py
This PR follows the path of #115 and moves transformation logic for floors out of the extractor and into the transformer.
> move floors transformation logic out of extractor

- python/src/energuide/dwelling.py
- python/src/energuide/extracted_datatypes.py
- python/src/energuide/snippets.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
- python/tests/test_snippets.py
This PR also moves some transformation logic out of the extractor for Walls.
> move walls transformation logic out of extractor

- python/src/energuide/dwelling.py
- python/src/energuide/extracted_datatypes.py
- python/src/energuide/snippets.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
- python/tests/test_snippets.py
This PR moves more transformation logic out of the doors extractor.
> move transformation logic for doors

- python/src/energuide/dwelling.py
- python/src/energuide/extracted_datatypes.py
- python/src/energuide/snippets.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
This PR adds functionality to interpret and load ventilation data.
https://trello.com/c/b3f6B3k8/111-extract-load-ventilation-data
> Load ventilation

- python/src/energuide/dwelling.py
- python/src/energuide/extracted_datatypes.py
- python/src/energuide/snippets.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
- python/tests/test_snippets.py
Similar to #121 and other PRs, this PR moves some transformation logic out of the window extraction into the transformer.
> moving window transformation logic out of extractor

- python/src/energuide/dwelling.py
- python/src/energuide/extracted_datatypes.py
- python/src/energuide/snippets.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
- python/tests/test_snippets.py
Similar to #123, this PR moves HeatedFloor transformations out of the extractor and into the transformer.
> move heated floor transformation out of extraction

- .circleci/config.yml
> Run the frontend integration tests on the CI

- python/src/energuide/embedded/area.py
- python/src/energuide/embedded/distance.py
- python/src/energuide/embedded/insulation.py
- python/src/energuide/extracted_datatypes.py
- python/tests/embedded/test_area.py
- python/tests/embedded/test_distance.py
- python/tests/embedded/test_insulation.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
This PR extracts the common concepts of area, distance, and insulation out of the `Ceiling` class. This simplifies things like property access and encapsulates metric to imperial conversions. Should help to clean up the other uses of these properties, starting with Ceiling to demonstrate.
> extract area, distance and insulation concepts from ceiling

- .circleci/config.yml
- api/package.json
- api/src/schema/__tests__/schema.test.js
- api/src/schema/index.js
- api/src/schema/resolvers.js
- api/test/queries.test.js
- api/yarn.lock
The pagination system implemented here is one based on cursors but trying to maintain enough simplicity that this remains plausibly usable for people without needing much (any?) explanation.
The return type of dwellingsInFSA has been changes to be a PaginatedResultSet, and it now accepts two optional arguments: limit and next.
> Add pagination

- .circleci/config.yml
- api/Dockerfile
* builds/deploys docker image on master only
* set semver in config.yml 
* uses circleci UI for variables
> Deploy to docker

- api/src/schema/__tests__/schema.test.js
- api/src/schema/index.js
Expose the heated floor area data via graphql!
> Add HeatedFloorArea type

- api/src/schema/index.js
> Add closing bracket that broke the world.

- python/src/energuide/snippets.py
- python/tests/test_snippets.py
This PR extracts `Basement` nodes from the xml
https://trello.com/c/MHCxw57a/107-extract-load-basement-data
> Extract basement

- api/src/schema/__tests__/schema.test.js
- api/src/schema/index.js
Add "waterheatings" to evaluation type.
> Add waterheatings to evaluation type

- python/src/energuide/dwelling.py
- python/src/energuide/embedded/window.py
- python/src/energuide/extracted_datatypes.py
- python/tests/embedded/test_window.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
Move Window into its own module.
> refactor Window

- python/src/energuide/dwelling.py
- python/src/energuide/embedded/door.py
- python/src/energuide/extracted_datatypes.py
- python/tests/embedded/test_door.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
> refactor Door

- api/.editorconfig
Editorconfig is a way to set editor settings for a project.
Read more: http://editorconfig.org/
> Add editorconfig file

- README.md
Add instruction how install app on windows computer
> Add window installation

- python/tests/randomized_energuide_data.csv
This PR adds <Floor> tags to the XML contained in `python/tests/randomized_energuide_data.csv`
> Add floor test data

- api/src/schema/__tests__/schema.test.js
- api/src/schema/index.js
- api/test/queries.test.js
As advertised, exposes newly added floor data via the schema.
> Expose floor data in the schema

- python/src/energuide/cli.py
- python/src/energuide/logging.py
This PR further pulls off a small section of #168.
A logging module is added, and small status messages are output at the beginning and end of CLI commands.
> Introduce logging

- python/src/energuide/dwelling.py
- python/src/energuide/exceptions.py
- python/src/energuide/extractor.py
- python/src/energuide/reader.py
- python/tests/test_dwelling.py
- python/tests/test_extractor.py
This PR starts peeling off sections of #168. It adds a new file that stores custom exceptions used in `energuide`
> centralize custom exceptions

- python/src/energuide/cli.py
- python/src/energuide/embedded/ceiling.py
- python/tests/embedded/test_ceiling.py
This PR continues factoring out sections of #168. Specifically this PR starts to implement usage of the new exception structure that was created in previous PR.
> Ceiling exception

- python/src/energuide/embedded/door.py
- python/tests/embedded/test_door.py
Next PR in the series of #168. Exception handling for `Door`s
> add door exception handling and tests

- python/src/energuide/dwelling.py
- python/src/energuide/embedded/ventilation.py
- python/src/energuide/extracted_datatypes.py
- python/tests/embedded/test_ventilation.py
- python/tests/test_dwelling.py
- python/tests/test_extracted_datatypes.py
Move ventilation into its own module.
> Refactor ventilation

- extract_endpoint/HelloWorld.py
Lets make a home for the extract endpoint microservice & greet the world 🎉
> Begin setting up extract_endpoint 

- python/tests/embedded/test_ceiling.py
- python/tests/embedded/test_door.py
Refactor `door` and `ceiling` bad data tests due to offline feedback.
> rewrite bad data tests

- python/src/energuide/embedded/code.py
- python/tests/embedded/test_code.py
Add exception handling and bad data tests to `WallCode` and `WindowCode`
> Codes exception handling

- python/src/energuide/embedded/floor.py
- python/tests/embedded/test_floor.py
add floor exception handling and tests
> Floor exceptions

- python/src/energuide/embedded/wall.py
- python/tests/embedded/test_wall.py
Add wall exception handling and tests
> Wall exceptions

- .circleci/config.yml
This PR adds a circleCI step for extract_endpoint 🎉  I think with this step the folder should be a good starting point for @sastels to start adding his code
To-do: An extract_endpoint_integration step will eventually need to be added but I'm not sure what that looks like yet
> Circleci for endpoint

- python/src/energuide/embedded/heated_floor_area.py
- python/tests/embedded/test_heated_floor_area.py
Add heated floor area exception handling and tests
> HeatedFloorArea exceptions

- python/src/energuide/embedded/ventilation.py
- python/tests/embedded/test_ventilation.py
Add ventilation exception handling and tests
> Ventilation exceptions

- python/src/energuide/embedded/water_heating.py
- python/tests/embedded/test_water_heating.py
Add water heating exception handling and tests
> WaterHeating exceptions

- python/src/energuide/embedded/window.py
- python/tests/embedded/test_window.py
Add window exception handling and tests
> Window exceptions

- api/src/utilities.js
Make the three `if` statements into one `for` loop with some variables.
> DRY up the filter code

- .circleci/config.yml
- extract_endpoint/requirements.txt
- extract_endpoint/setup.py
(with @evadb, code originally part of pull request #196  ) 
Add `setup.py` for `extract_endpoint` and install it in CircleCI.
> Install extract_endpoint

- etl/src/energuide/dwelling.py
- etl/src/energuide/exceptions.py
- etl/src/energuide/reader.py
- etl/src/energuide/transform.py
- etl/tests/test_transform.py
This PR adds code to catch exceptions in `transform.run` and log them instead of halting execution.
> Log exceptions

- etl/src/energuide/element.py
- etl/tests/test_element.py
This PR adds a couple of needed methods to `Element`. Simple programmatic creation of a new node, and some basic node manipulation methods.
> add Element.new and Element.insert methods

- etl/src/energuide/dwelling.py
- etl/src/energuide/element.py
- etl/src/energuide/embedded/ceiling.py
- etl/src/energuide/embedded/code.py
- etl/src/energuide/embedded/door.py
- etl/src/energuide/embedded/floor.py
- etl/src/energuide/embedded/heated_floor_area.py
- etl/src/energuide/embedded/ventilation.py
- etl/src/energuide/embedded/wall.py
- etl/src/energuide/embedded/water_heating.py
- etl/src/energuide/embedded/window.py
- etl/src/energuide/exceptions.py
- etl/src/energuide/extractor.py
- etl/src/energuide/transform.py
- etl/tests/embedded/test_ceiling.py
- etl/tests/embedded/test_code.py
- etl/tests/embedded/test_door.py
- etl/tests/embedded/test_floor.py
- etl/tests/embedded/test_heated_floor_area.py
- etl/tests/embedded/test_ventilation.py
- etl/tests/embedded/test_wall.py
- etl/tests/embedded/test_water_heating.py
- etl/tests/embedded/test_window.py
- etl/tests/test_dwelling.py
- etl/tests/test_extractor.py
- etl/tests/test_transform.py
Whoops. #215 merged to the wrong branch again.
> rename *Exception to *Error

- etl/src/energuide/exceptions.py
Exactly as the title suggests.
> include optional exception message for greater readability

- etl/src/energuide/embedded/basement.py
- etl/tests/embedded/test_basement.py
This PR prepares `embedded.basements` for the addition of crawlspace and slab parsing.
> Foundation Types

- extract_endpoint/src/HelloWorld.py
- extract_endpoint/tests/test_basic.py
Delete the files we used to ensure that the project was set up in CI correctly.
> remove testing files

- etl/src/energuide/dwelling.py
- etl/src/energuide/embedded/heating.py
- etl/tests/embedded/test_heating.py
- etl/tests/test_dwelling.py
This PR takes the newly-added `Heating` element and adds it to the data to be loaded to MongoDB.
Fixed a couple of broken windows on the way.
> load heating data

- api/src/schema/index.js
- api/src/schema/resolvers.js
- api/test/queries.test.js
This makes our schema language consistent.
> Rename evaluationsFor to just dwelling

- etl/pylintrc
- etl/src/energuide/embedded/basement.py
- etl/tests/embedded/test_basement.py
This PR adds additional functionality to `basements` to also parse crawlspace data.
> Parse crawlspaces

- api/src/schema/index.js
- api/src/schema/resolvers.js
- api/test/queries.test.js
Behold!
```
filters: [{field: dwellingCity comparator: eq value: "Charlottetown"}]
```
> Allow for multiple filters

- etl/src/energuide/embedded/basement.py
- etl/tests/embedded/test_basement.py
This PR adds functionality to parse the `Slab` foundation types.
> Parse slabs

- etl/pylintrc
- etl/src/energuide/dwelling.py
- etl/tests/test_dwelling.py
This PR adds basement, crawlspace, and slab foundation elements to transform pipeline
> Transform foundations

- etl/src/energuide/dwelling.py
- etl/src/energuide/extractor.py
- etl/tests/test_cli.py
- etl/tests/test_dwelling.py
- etl/tests/test_extractor.py
Add testing for ERSRATING when value is empty
> test ersrating when extract from csv file

- api/src/schema/enums.js
- api/src/schema/index.js
- api/src/schema/resolvers.js
- api/test/enum.test.js
As advertised. This makes more fields available to filter by.
> Add enum functions for WaterHeater Type

- etl/src/energuide/cli.py
- etl/src/energuide/database.py
- etl/src/energuide/transform.py
- etl/tests/test_cli.py
- etl/tests/test_transform.py
This PR adds functionality to drop the collection by default before loading
> Drop collection before load

- api/test/queries.test.js
This PR adds two integration tests
- 1 for `heatedFloorArea`
- 1 for `ventilations`
> Add two more integration tests.

- api/test/queries.test.js
> Update tests that reference non-existant fields

- api/src/schema/enums.js
- api/src/schema/index.js
- api/src/schema/resolvers.js
- api/test/enum.test.js
Create functions for wall type and add them to the enum so that they are options on the filter field.
> Add enum functions for wall type

- etl/src/energuide/extractor.py
- etl/tests/test_cli.py
- etl/tests/test_extractor.py
This PR adds missing required CSV fields, as well as purging fields of the CSV data that are not in our list of required columns.
> Require more CSV fields

- etl/src/energuide/extractor.py
- etl/src/energuide/snippets.py
- etl/tests/randomized_energuide_data.csv
- etl/tests/test_snippets.py
This PR contains the extraction components of PR #253
> extract energy upgrade nodes

- etl/src/energuide/dwelling.py
- etl/src/energuide/extractor.py
This PR adds heating_system to Evaluation
> Serialize heating_system

- api/src/schema/__tests__/schema.test.js
- api/src/schema/index.js
- api/src/schema/resolvers.js
- api/test/queries.test.js
Exposing upgrade data via the schema.
> Add upgrades to schema

- .circleci/config.yml
- etl/tests/test_validator.py
- scripts/notify_failure.sh
This PR adds a notification to the NRCan slack channel when the master branch fails CI.
Currently only added to the `etl` job while the exact message and mechanism is worked out.
> Slack notification

- etl/src/energuide/extractor.py
- etl/tests/test_extractor.py
This PR adds a step to the extraction to convert empty strings in the input to `None` values.
> Extract empty strings as None

- api/src/schema/__tests__/schema.test.js
- api/src/schema/index.js
- api/test/queries.test.js
And finally, the number at the heart of all this; the rating!
> Add energuide rating to schema

- .circleci/config.yml
- extract_endpoint/Dockerfile
This PR adds a job called deploy_endpoint to CircleCI which will build a docker image and push it to Docker Hub on each commit to master.
> Deploy Endpoint, Add Dockerfile

- api/src/schema/__tests__/schema.test.js
- api/src/schema/index.js
- api/test/queries.test.js
This is baller.
Hats off to @buckley-w-david.
> Return fileId from the API

- api/src/schema/enums.js
- api/src/schema/index.js
- api/src/schema/resolvers.js
- api/test/enum.test.js
Allow users to filter by door attributes.
> Add enum functions for doors

- .circleci/config.yml
This PR adds the `version` specification back to the `workflows:` section which was accidentally remove in https://github.com/cds-snc/nrcan_api/commit/659bae504846972c97b135a2bf2613e15f0cae94
It also removes a lot of trailing whitespace on lines due to how my editor is setup.
> Add version

- etl/src/energuide/extractor.py
- etl/tests/test_extractor.py
Simplifying the extractor a bit, cleaning up a bit of technical debt here to make it easier to hack on.
> remove drop_fields

- api/src/schema/types/FoundationFloor.js
- api/src/schema/types/__tests__/FoundationFloor.test.js
Another in the now established tradition of types that are not being
used yet, but will be soon...
> Add FoundationFloor type

- etl/requirements.txt
- etl/src/energuide/extractor.py
This PR adds a progress indicator to the extraction function using `tqdm`. This is a nice feature that helps avoid the "is this thing working" symptom.
This PR also simplifies the extraction functions a bit, so they don't pass generators to functions and return generators needlessly. Just with a bit of simple refactoring, we get precisely the same result but with less embedded blocks.
> extractor progress bar

- etl/src/energuide/embedded/basement.py
- etl/tests/embedded/test_basement.py
I stumbled over this in the API and thought I would change it, since it's a plurality of walls anyway.
> Rename Foundation wall to walls

- api/src/schema/__tests__/schema.test.js
- api/src/schema/index.js
- api/src/schema/types/Foundation.js
- api/src/schema/types/__tests__/Foundation.test.js
- api/test/queries.test.js
> Add foundations to schema

- etl/src/energuide/dwelling.py
- etl/src/energuide/extractor.py
- etl/src/energuide/reader.py
- etl/src/energuide/transform.py
- etl/tests/test_dwelling.py
- etl/tests/test_extractor.py
- etl/tests/test_reader.py
This was giving me some cyclical dependencies as I tried to refactor the `reader.py` file away. It's of limited short-hand ability anyway, so :fire: for now/forever.
> replace reader.InputData with Dict[str, Any]

- etl/src/energuide/cli.py
- etl/src/energuide/extractor.py
- etl/tests/test_cli.py
- etl/tests/test_extractor.py
This PR catches errors thrown in other parts of the extractor line-by-line process, logs them to the output, and completes the extraction process.
> better extractor logging & error handling

- etl/src/energuide/cli.py
- etl/src/energuide/extractor.py
- etl/src/energuide/transform.py
- etl/tests/test_transform.py
This PR adds the ability to optionally hide the progress bar when extracting the data, primarily since it makes test output noisy for no benefit.
> optionally hide the progress bar for loading

- api/package.json
> Engerguide -> EnerGuide

- etl/src/energuide/element.py
This PR changes Element.get exception raising to using built-in exception chaining
> chain exceptions in Element.get

- etl/Dockerfile
Simple update to Dockerfile to add a start CMD.
> add start CMD

- etl/src/energuide/embedded/heating.py
This PR adds more exception handling to Heating
> Add more thorough exception handling to Heating

- etl/src/energuide/embedded/water_heating.py
- etl/tests/embedded/test_water_heating.py
- etl/tests/test_dwelling.py
This PR adds an additional field for the efficiency of the Drain Water Heat Recovery system (if present).
> Drain water heat recovery

- etl/src/energuide/logger.py
- etl/src/energuide/transform.py
- etl/tests/test_logger.py
This PR improves the logging in the transform stage.
Caught exceptions during transformation are unwrapped and then added to the log message.
> Unroll exception messages

- extract_endpoint/README.md
> Extract endpoint readme first draft

- extract_endpoint/README.md
Some instructions for running everything (post / endpoint / tl app) locally.
> Docs for running everything locally

- extract_endpoint/src/extract_endpoint/endpoint.py
- extract_endpoint/src/extract_endpoint/post_to_endpoint.py
- extract_endpoint/tests/test_endpoint.py
- extract_endpoint/tests/test_post_to_endpoint.py
add a "run_tl" command to `post_to_endpoint.py`.
> Add a manual run_tl trigger

- etl/src/energuide/cli.py
- etl/src/energuide/database.py
- etl/src/energuide/flask_app.py
- etl/tests/test_cli.py
- etl/tests/test_database.py
This PR implements the changes suggested by @JasonMWhite 
Instead of dropping the collection and loading from scratch (resulting in some downtime), load now updates each record in place, creating new ones if needed.
> Update in place

- etl/Dockerfile
- etl/requirements.txt
- extract_endpoint/Dockerfile
- extract_endpoint/requirements.txt
> change gunicorn worker type

- extract_endpoint/src/extract_endpoint/endpoint.py
- extract_endpoint/src/extract_endpoint/logger.py
Do some proper logging in the Endpoint. 
Ended up just copying over `energuide/logger.py` rather than mess around with installing energuide in endpoint.
> Added logging to endpoint

- etl/src/energuide/database.py
Change logging message to remove potential logging of sensitive info
> Change logging message

- extract_endpoint/src/extract_endpoint/endpoint.py
Ensure endpoint returns if anything goes wrong when connecting to TL.
> make endpoint less crashy

- etl/src/energuide/flask_app.py
This will allow us to run locally as well as in production.
> use ENERGUIDE_PRODUCTION environment variable

- etl/src/energuide/flask_app.py
- etl/tests/test_flask_app.py
- extract_endpoint/src/extract_endpoint/endpoint.py
- extract_endpoint/src/extract_endpoint/post_to_endpoint.py
- extract_endpoint/tests/test_endpoint.py
- extract_endpoint/tests/test_post_to_endpoint.py
Add routes to get the status of the apps and a related cli command.
possible status values are idle, busy, Error, and Unknown (the latter is the TL status if Endpoint has crashed)
> System status

- extract_endpoint/README.md
add some documentation concerning deploying the system.
> Some deploy docs

- README.md
This PR makes some edits to the Windows setup instructions to improve clarity and fix small errors.
> Update windows instructions

- nrcan_etl/src/energuide/logger.py
- nrcan_etl/tests/test_logger.py
This PR extracts the logging from #392 
It is identical to the logging in `etl`
> Add Logger

- nrcan_etl/src/energuide/database.py
- nrcan_etl/tests/conftest.py
- nrcan_etl/tests/test_database.py
This PR adds the database code from #392 
It is identical to what is in `etl`
> Add Database

- nrcan_etl/tests/test_database.py
This PR adds a missing argument to the `Dwelling` constructor in the database.py tests
> Fix master

- nrcan_etl/src/energuide/transform.py
- nrcan_etl/tests/conftest.py
- nrcan_etl/tests/test_transform.py
This PR adds the transform code from #392 
It is mostly the same as what is in `etl`, with slight adjustments to the tests to reflect that the data is different.
> Add transform

- nrcan_etl/src/energuide/embedded/upgrade.py
This PR updates the upgrade priority property parsing to use `Element.get`, which results in nicer looking code with better error reporting.
> Nicer upgrade property parsing

- nrcan_etl/src/energuide/dwelling.py
- nrcan_etl/tests/test_dwelling.py
ADD fields to transform & load
> Add design heat loss fields to transform and load

- nrcan_etl/src/energuide/dwelling.py
- nrcan_etl/src/energuide/embedded/evaluation_type.py
This is the same as #414, which was accidentally merged into a branch other than master
> Add F evaluation type

- nrcan_etl/src/energuide/embedded/walls.py
This PR changes "composition" to "composite", which better represents what the data is (They are composite values).
> change composition to composite

- README.md
This PR makes minor changes to the README to adapt it to the new `nrcan_etl`
> adapt README to new nrcan_etl

- nrcan_etl/src/energuide/dwelling.py
- nrcan_etl/src/energuide/embedded/measurement.py
- nrcan_etl/tests/test_dwelling.py
This PR improves the to_dict tests for Dwelling and Evaluation to properly test all elements.
> improve to_dict tests for Dwelling and Evaluation

- nrcan_etl/src/energuide/extractor.py
Seems we are pulling the wrong postal code, 
MAIL_PCODE: Homeowner mailing postal code for incentive
CLIENTPCODE: Home postal code
This PR fixes that
> use CLIENTPCODE instead of MAIL_PCODE

- .circleci/config.yml
This PR will deploy `nrcan_etl` instead of `etl`
> set working_dir to nrcan_etl

- .circleci/config.yml
Reverts cds-snc/nrcan_api#452
Emergency revert due to failed master
> Revert "set working_dir to nrcan_etl"

- .circleci/config.yml
- nrcan_etl/sshd_config
Redo of #452 with missing sshd_config file added
> change deploy to nrcan_etl

- nrcan_etl/tests/embedded/test_evaluation_type.py
- nrcan_etl/tests/embedded/test_region.py
This PR tightens up some tests for the enums, making sure to exercise each possible value at least once.
> Even moar testing

- nrcan_etl/src/energuide/embedded/walls.py
- nrcan_etl/tests/embedded/test_walls.py
This PR adds some missing exceptional case handling and testing to the Wall embedded datatype.
> Wall exception handling

- resource/etl_ingress.md
This PR adds a document to give a small bit of guidance on what needs to be written to generate files for ingress to the ETL.
This PR address issue https://github.com/cds-snc/nrcan_api/issues/459
> ETL ingress documentation

- resource/add_to_api.md
exactly what is says on the tin
or is it
🤔
> Add instructions to add field to API

- api/docs.md
Now that all the translations are in, I've regenerated the fields document
> Regenerate documents

- docs/using_the_api.md
An epic guide written by yours truly 🎉
> How to use the api

- docs/README.md
This is a huge PR, I know, but extremely necessary.
Adding my glorious new document to the central document readme
> Add to the central readme

- docs/using_the_api.md
the biggest PR of this project
> Fix link to docs in using api document

- docs/add_to_api.md
We've gone too many layers deep
> Add documentation about documentation

- docs/using_the_api.md
> Document navigating pagination

- docs/using_the_api.md
This PR takes a stab at addressing comments raised in https://github.com/cds-snc/nrcan_api/issues/479
> Addressing Paul's comments

- api/test/enum.test.js
These generated tests were always a bit painful, and not amazing at
communicating what had broken. Finally cleaning them up.
> Refactor enum tests

- api/src/__tests__/server.test.js
This is a little cleanup prepping for further work.
> Refactor server tests
