package.json
yarn.lock

The lingui-cli gives tools to extract i18n messages and compile them for
use. This commit adds the module and `yarn extract` and `yarn compile`
scripts to use them.

Add lingui-cli tools and npm scripts

---

.circleci/config.yml
.gitignore
python/README.md
python/requirements.txt
python/setup.py
python/src/energuide/cli.py
python/tests/test_basic.py

Adds basic Python scaffolding to a separate folder within this repo. Also adds to CircleCI - Node & Python now run in parallel in a workflow.
/cc @sleepycat @evadb

add python scaffolding

---

python/src/energuide/database.py

bulk_write is typically for mixed writing operations (update, delete, insert), while insert_many does just inserts. Since we are doing just inserts insert_many seems more appropriate.

change bulk_write to insert_many

---

python/src/energuide/database.py
python/src/energuide/transform.py
python/tests/conftest.py
python/tests/test_database.py
python/tests/test_transform.py

Splits up the existing `load` step, which: 
- given a path, opens a file
- interprets in into a DataFrame
- does some cleanup on that DF
- loads it into Mongo
Removed some (I believe) currently unnecessary functionality to simplify. This will give us a hook to start Transforming the DataFrame(s) between Reading and Loading.

split load into transform and load

---

python/src/energuide/database.py
python/src/energuide/transform.py
python/tests/conftest.py
python/tests/test_database.py
python/tests/test_transform.py

Our existing test fixtures had a side-effect - they were creating a database that was not then torn down when done. This is a bad pattern - it can lead to flaky tests that are hard to diagnose.
The existing tests were getting around it by making sure to tear down the database at the beginning of the test, but that's too easy to forget to do. This way it is a fresh database each time, with no possibility of colliding with an existing database used for dev purposes on a local install.

clean up database creation on fixture teardown

---

python/src/energuide/cli.py
python/tests/test_cli.py

This PR adds a `load` subcommand (the first) to the `energuide` main command. It loads the supplied filename to the specified (through environment variables or command-line options) mongodb collection.

add cli load command

---

python/pylintrc
python/src/energuide/dwelling.py
python/tests/test_dwelling.py

Adds a new `Dwelling` class to be used by the transform logic. Right now it only extracts a single field, but we will add on to this class as we go. Also, this will serve as a great logical interface point for loading an iterable of `Dwelling`s to MongoDB.

add Dwelling class

---

python/src/energuide/dwelling.py
python/tests/test_dwelling.py

This PR brings us up to feature parity with the existing `transform` capability around data scrubbing. Adds city, province, postal code, and year the house was built to the main `Dwelling` class.

adding regional information and year_built fields

---

python/src/energuide/dwelling.py
python/src/energuide/interpreter.py
python/tests/test_dwelling.py
python/tests/test_interpreter.py

With the exception of adding `to_dict` methods to `Evaluation` and `Dwelling`, this PR just moves functionality out of the `dwelling` module to the new `interpreter` module.
The logic here is that there is a first step for validating and parsing the raw data (including converting raw strings to datetimes, custom enums, etc). This is now handled in the `interpreter` module. This is distinct from the `dwelling` module that handles the hierarchical nature of the data structures.
Still not completely satisfied with the way it's laid out (custom types mixed in with datetimes, etc), but it's a step in the right direction. The PR is a bit bigger than I usually like, but most of it is cut/paste from one module to another.

add to_dict, split up dwelling

---

package.json

This script runs jest with nodes `--inspect-brk` flag set allows
debugging via the Chrome Devtools.

Add debug script: yarn run dbg

---

src/schema/resolvers.js
src/utilities.js
test/queries.test.js
test/utilities.test.js

This commit ensures that filters that include multiple (likely
contadictory) comparison operators are rejected:
{field: yearBuilt gt: "1979", eq: "1979"}
In this situation the correct thing would be to return an error, which
is now what happens.

Add checks for multiple filters

---

python/src/energuide/dwelling.py
python/tests/test_dwelling.py

Minor refactor of Dwelling to accept `List[InputRow]` and return a single `Dwelling`.

refactor dwelling

---

src/schema/index.js
src/schema/resolvers.js
src/schema/types/ForwardSortationArea.js
test/ForwardSortationArea.test.js
test/queries.test.js

The first three letters of a postal code are known as the Forward
Sortation Area. This commit adds a function to retrieve data using the
FSA and a custom type so we can accept that safely.

Retrieve data using first 3 postal code characters

---

.circleci/config.yml

This pull request creates an additional 2 circleci jobs that are meant for integration testing of the ETL and API components.
`python_integration` job loads data from a CSV into a mongo database, then exports that database.
`node_integration` job then imports that data into the mongo database for that job. Currently it then just echo's "Hello World!", further work required from the API side in constructing tests to slot into this new job.

CI API integration

---

src/schema/types/PostalCode.js
test/PostalCode.test.js

parseValue is handed a single value while parseLiteral is passed a
chunk of the AST. Handling these properly now.

Fix parseValue function for PostalCode type

---

src/schema/types/ForwardSortationArea.js
test/ForwardSortationArea.test.js

As advertised: proper implementations of parseValue and parseLiteral for the Forward Sortation Area Type.

Properly handle both values and literals for FSA

---

python/requirements.txt
python/src/energuide/extractor.py
python/src/energuide/snippets.py
python/tests/test_extractor.py
python/tests/test_snippets.py

This PR adds the first XML parsing to the extractor. It pulls out all the `ceilings` data and adds it to each row. The data is a list of dicts containing all the needed information from each ceiling.

pull ceilings data out of raw_xml in extractor

---

python/src/energuide/dwelling.py
python/src/energuide/extractor.py
python/src/energuide/snippets.py
python/tests/test_dwelling.py
python/tests/test_snippets.py

This PR:
- adds area and length to the extracted ceiling information
- renames `ForwardSortationArea` to `forwardSortationArea` to be consistent with `ceilings`
- updates the ceilings snippets test to be more specific about the extracted data
- updates tests & test fixtures accordingly to the above

include ceiling measurements in extracted data

---

python/README.md

This pull request adds some information to the python README about the newly added extract CLI command

add instructions for extract cli command to README

---

python/pylintrc
python/src/energuide/snippets.py
python/tests/test_snippets.py

This PR requires changing the base to master before merging.
This PR adds the ability to extract wall details from the house components. Combined with the new wall codes information, this provides all the wall information present in the HOIS.

extract wall details

---

package.json
src/__tests__/server.test.js
src/__tests__/utilities.test.js
src/schema/types/__tests__/ForwardSortationArea.test.js
src/schema/types/__tests__/Latitude.test.js
src/schema/types/__tests__/Longitude.test.js
src/schema/types/__tests__/PostalCode.test.js

The idea here is to colocate the unit tests with the code under tests,
which is generally what Facebook crew is reccomending. The integration
test, which test more than one piece of code then live in the the `test`
folder.
Integration tests can now be run with `yarn integration` while unit
tests can be run with `yarn test` as normal.
Ping @buckley-w-david. Next stop, CircleCI.

Separate integration tests from unit tests

---

python/src/energuide/dwelling.py
python/src/energuide/extracted_datatypes.py
python/tests/randomized_energuide_data.csv
python/tests/test_dwelling.py
python/tests/test_extracted_datatypes.py

This PR factors out the `Wall` class and it's usage from #79 
It also modifies the test fixture data somewhat to add a wall to one of the entries that uses a code, instead of just being User Specified.

load wall data

---

python/src/energuide/snippets.py
python/tests/test_snippets.py

This PR adds extraction of the raw `door` data. `Door`s are always embedded within a `Wall`, which makes logical sense.
https://trello.com/c/L9320zNP/106-extract-load-door-data

extract exterior doors

---

python/src/energuide/extracted_datatypes.py
python/tests/test_extracted_datatypes.py

This PR factors out some misc test improvements, as well as adds the `nullable` keyword to the schema of the types in extracted_datatypes marking them as possibly `None`.
This functionality was factored out of #79

Improve extracted_datatypes

---

api/src/__tests__/utilities.test.js
api/src/schema/resolvers.js
api/src/utilities.js

There was far to much going on in there. Extracted the construction of
the MongoDB query object in to a separate tested function in the
utilities module.

Extract query construction logic from resolver

---

python/src/energuide/snippets.py
python/tests/test_snippets.py

This PR changes the xpath search string for door and window components to search for a node at any depth in the tree beneath the components node.
This is because there are many possible valid paths to those nodes that were not captured with the previous configuration (such as Basement->Wall->Door->Window)

Update door and window xpath string

---

api/src/schema/index.js
api/src/schema/resolvers.js
api/test/queries.test.js

Previously we were thinking that a combination of account number/houseId
plus postal code. This seems to be simpler and just as effective.

Lookup individual dwelling details by account only

---

python/src/energuide/extractor.py
python/src/energuide/snippets.py
python/tests/test_snippets.py

This PR refactors `snippets.py` to use `lxml.etree` and `xpath()` to extract information from the source document.

refactor snippets to use xpath

---

python/src/energuide/snippets.py
python/tests/test_snippets.py

This PR extracts the raw `heating_cooling` xml from the source, as discussed. We will parse this raw input in the transform logic to derive the necessary attributes.

extract heating_cooling raw xml

---

python/src/energuide/dwelling.py
python/src/energuide/validator.py
python/tests/test_dwelling.py
python/tests/test_validator.py

This PR adds (and switches to) a custom validator with support for a new data type: `xml`, and a new coercion option `parse_xml`.

custom validator

---

python/src/energuide/dwelling.py
python/src/energuide/extracted_datatypes.py
python/src/energuide/extractor.py
python/src/energuide/snippets.py
python/tests/test_dwelling.py
python/tests/test_snippets.py

This PR refactors the snippets module to replace the dictionaries with NamedTuples to allow for more strict static type checking
This PR is larger than I would like, but the majority of it are things like class definitions, which does inflate the line count.

refactor snippets

---

api/src/utilities.js
api/test/queries.test.js

Filter values are passed as strings. This commit converts the value to the appropriate data type so mongo can find things.
There is some repeated logic here, but we are going to loop back and DRY it up shortly.

Handle different data types handed to filters

---

python/src/energuide/element.py

Exposes `_Element.attrib` through `element.Element`, to allow us to replace calls like:
```
node.xpath('@foo')[0]
```
with
```
node.attrib['foo']
```

expose _Element.attrib

---

python/src/energuide/dwelling.py
python/src/energuide/extracted_datatypes.py
python/src/energuide/snippets.py
python/tests/test_dwelling.py
python/tests/test_extracted_datatypes.py
python/tests/test_snippets.py

This PR was hard to break up, but it's just taking the same approach as all the other similar PRs (e.g. #125). It moves a bunch of logic out of the extractor and into the transfomer.

refactor wall and window codes transformation logic out of extractor

---

python/mypy.ini
python/src/energuide/element.py
python/src/energuide/extracted_datatypes.py
python/src/energuide/validator.py
python/tests/test_cli.py
python/tests/test_element.py
python/tests/test_extracted_datatypes.py
python/tests/test_extractor.py
python/tests/test_validator.py

This PR turns on the `strict_optionals` flag for mypy, which differentiates between things like `Optional[str]` and `str`.
Also added a couple of tests for `element.Element` because I added a custom function.

add Element tests, turn on strict optionals

---

python/src/energuide/extractor.py
python/src/energuide/snippets.py
python/tests/sample.h2k
python/tests/test_cli.py
python/tests/test_extractor.py
python/tests/test_snippets.py

This PR adds functionality for as much water heating extraction as we currently have the information to do.
There exists a property in the `Primary` and `Secondary` water heater nodes (`hasDrainWaterHeatRecovery`) which indicates that an additional row is to be extracted from this node. We do not have the required information to know what that node looks like until we get more sample data that has an example of it. As such that is not being extracted.
An assertion to the water_heating extraction test is to indicate this field is `"false"`, when we have data that has these extra rows it will fail the tests and we can add in the required functionality.
https://trello.com/c/pqClWxf9/110-extract-load-water-heating-data

Water heating extraction

---

Makefile
api/Makefile
python/Makefile

This pull request splits up the Makefile logic into the directories where the commands will be run.
I'm going to add more rules in here so that new devs can get up and running more quickly and it felt like trying to break down the complexity of the one big Makefile at the top level will help with that.
Opinions welcome.

Make more makefiles

---

python/src/energuide/element.py
python/src/energuide/extractor.py
python/src/energuide/snippets.py
python/tests/test_element.py
python/tests/test_snippets.py

This PR replaces the last of the `lxml._Element` uses in the codebase with `element.Element` for type checking greatness.

replace more uses of _Element

---

python/pylintrc
python/src/energuide/dwelling.py
python/src/energuide/extracted_datatypes.py
python/src/energuide/snippets.py
python/tests/test_dwelling.py
python/tests/test_extracted_datatypes.py

This PR adds functionality to transform and load water heating data.
While the line count is much larger than I would like, it is artificially inflated by a very large enum created to store all 79 possible type values for water heating, that are derived from the energy type and the tank type.

Load water heating

---

python/src/energuide/snippets.py
python/tests/test_snippets.py

I noticed that the inferred types here were all just `list`, so it wasn't detecting Nones being assigned to a `str` NamedTuple value. This PR corrects this.

make snippets more typesafe

---

python/src/energuide/dwelling.py
python/src/energuide/embedded/ceiling.py
python/src/energuide/extracted_datatypes.py
python/tests/embedded/test_ceiling.py
python/tests/test_dwelling.py
python/tests/test_extracted_datatypes.py

I've been uncomfortable with the `extracted_datatypes` module for a while, so this is the first step in moving `Ceiling` out to `embedded/ceiling.py`. Also tightens up the tests on `Ceiling` a bit.

move ceiling out to its own module

---

python/src/energuide/dwelling.py
python/src/energuide/embedded/floor.py
python/src/energuide/extracted_datatypes.py
python/tests/embedded/test_floor.py
python/tests/test_dwelling.py
python/tests/test_extracted_datatypes.py

Similar to #137 this PR moves `Floor` to its own module in `embedded/floor.py` for clarity and improved tests.

move floor to separate module

---

python/src/energuide/dwelling.py
python/src/energuide/embedded/wall.py
python/src/energuide/extracted_datatypes.py
python/tests/embedded/test_wall.py
python/tests/test_dwelling.py
python/tests/test_extracted_datatypes.py

Continuing from #139, this PR moves `Wall` out to its own module. Also now embeds the actual `WallCode` object directly in the named tuple, rather than storing separately the english and french versions of two properties.

move Wall to wall.py

---

python/src/energuide/snippets.py
python/tests/test_snippets.py

This PR extracts `Crawlspace` nodes from the xml.
These, along with `Basement` and `Slab` nodes all comprise the BASEMENT/FOUNDATION table
https://trello.com/c/MHCxw57a/107-extract-load-basement-data

extract crawlspace nodes

---

python/src/energuide/snippets.py
python/tests/test_snippets.py

This PR extracts `Slab` nodes from the xml.
These, along with `Crawlspace` and `Slab` nodes all comprise the BASEMENT/FOUNDATION table
https://trello.com/c/MHCxw57a/107-extract-load-basement-data

extract slab nodes

---

python/tests/test_extracted_datatypes.py

@sastels and I noticed this while solving some merge conflicts. Since Wall & Window were moved to their own tests, this should probably be removed too?

Remove unused extracted datatypes test code

---

.gitignore
Makefile
README.md
api/Makefile
bootstrap.sh
python/Makefile

**Note**
I closed the previous branch and then force-pushed which means I lost the comment history on the previous PR: #149. I've imperfectly recreated it below, so we don't lose context.
---
The "get up and going" process is (should be) much easier now.
The `./bootstrap.sh` file installs all the things we need to install once (pyenv, mongodb, etc), and then the Makefiles have all the commands we need to run multiple times.
- The `/python/Makefile` runs everything without tripping over virtualenv problems now.
- The `/api/Makefile` looks for an `NRCAN_ENGINE_API_KEY` to be set or else it won't run.
Also, I've tested this on my Macbook the best that I can. In theory, all the Makefile stuff should be able to run cross-platform, but I haven't been able to confirm that it does.

Add ./bootstrap.sh file, refactor Makefiles

---

api/src/schema/__tests__/schema.test.js
api/src/schema/index.js
api/test/queries.test.js

These integration tests assert against the actual values currently being
returned by the fixture data. If the data shifts, and the values change
(or are null) these tests will fail and stop the build/deployment
process.
In the end, the effect we were looking for was easy to get. :smile_cat:

Add integration tests that fail when data changes

---

README.md

This PR fixes a small bug in the README where it was linking back to the current page instead of localhost.

Add localhost link to README

---

.circleci/config.yml

This PR moves the branch filter from `deploy` to `yarn_build`.
With the previous (current) version while only master is getting deployed, every branch was being built during CI, which isn't really necessary.

only build master

---

api/package.json

1. Linting wasn't finding the files, so removing a `,` after `src/**,` in the package.json fixed it
2. Then it was finding some files we didn't want to lint, so I added a flag to ignore the autogenerated stuff in `locale`

Fix linting rules

---

.gitignore
Makefile
api/Makefile
api/package.json
api/yarn.lock

Currently, we have to kill the API and rebuild it whenever we make changes to the API code.
Now, by running `yarn watch`, we get the API rebuilding itself whenever there are changes to files in the `src/` directory (but not the `src/__tests__/` directory).

Add a `yarn watch` step to package.json

---

python/src/energuide/exceptions.py

This PR simplifies InvalidEmbeddedDataTypeException based on [PEP 3134](https://www.python.org/dev/peps/pep-3134/), and adds missing type hints.

Small exceptions change

---

api/src/schema/__tests__/schema.test.js
api/src/schema/index.js
api/test/queries.test.js
python/src/energuide/embedded/water_heating.py
python/tests/embedded/test_water_heating.py

tankVolumeGallon is not more important than any other tankVolume.
***
**WARNING**
You will need to drop the existing test data and reimport after merging this. 
If you are running on a macOS laptop, you can run `make setup` and then `make run` from the root folder.

Lowercase 'tankVolumeGallon' key in 'waterHeatings'

---

README.md
api/README.md

This PR updates the top-level README and the /api/README.
- I cleaned up some of the windows commands (which were hard to copy from with trailing comments)
- added `make watch`
- added instructions to install (and use) `yarn` rather than `npm`
- I added a 'get up and running quickly' section
- I fixed the curl request 
- I added the command for the yarn integration test

Readme cleanup/updates

---

api/test/enum.test.js

Previously these tests baked the houseId into the expectations. This
wasn't a core part of the tests (given that they are just testing that
the query object is usable by mongo), and assumes an order that appears
not to hold... sometimes...

Check that things are returned

---

.dockerignore
.gitignore
Makefile
README.md

Updates a few things that were broken or out of date after today's DirectoryRenameGate PR disaster.

Update root-level files now that `/python` directory is `/etl`

---

etl/src/energuide/dwelling.py
etl/src/energuide/element.py
etl/src/energuide/embedded/ceiling.py
etl/src/energuide/embedded/code.py
etl/src/energuide/embedded/door.py
etl/src/energuide/embedded/floor.py
etl/src/energuide/embedded/heated_floor_area.py
etl/src/energuide/embedded/ventilation.py
etl/src/energuide/embedded/wall.py
etl/src/energuide/embedded/water_heating.py
etl/src/energuide/embedded/window.py
etl/src/energuide/exceptions.py
etl/src/energuide/extractor.py
etl/src/energuide/transform.py
etl/tests/embedded/test_ceiling.py
etl/tests/embedded/test_code.py
etl/tests/embedded/test_door.py
etl/tests/embedded/test_floor.py
etl/tests/embedded/test_heated_floor_area.py
etl/tests/embedded/test_ventilation.py
etl/tests/embedded/test_wall.py
etl/tests/embedded/test_water_heating.py
etl/tests/embedded/test_window.py
etl/tests/test_dwelling.py
etl/tests/test_extractor.py
etl/tests/test_transform.py

See: https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions
> Most exceptions are defined with names that end in “Error,” similar to the naming of the standard exceptions.

rename *Exception to *Error

---

api/package.json

NPM scripts that require quotes need to be escaped double quotes to work properly on Windows.
With single quotes, Windows includes the single quote as part of the command (ie, it says it doesn't know how to run `'yarn`).
Also expanded the flags to make them more explicit.

Bigfix: updating NPM script for Windows compatibility

---

api/test/queries.test.js

Besides being duplicated, this test is now testing something that the
new filter format makes impossible.

Remove test for multiple comparators

---

etl/src/energuide/embedded/heating.py
etl/tests/embedded/test_heating.py

This PR adds the long-awaited Heating element. It isn't yet included in the actual transform operation, merely the ability to parse it from xml and serialize it with `to_dict`.
There are some known holes that I was not able to yet figure out - no known examples of electric baseboards, P9-11 efficiency heaters, or combo heating/water heater systems. The parsing logic should fail loudly with explicit error messages in these cases.

add heating element

---

etl/src/energuide/extractor.py
etl/tests/sample.h2k

This PR introduces small refactoring/changes to the ETL code to make it compatible with development on a Windows machine.
1. If an `OverflowError` occurs when setting the max field size, fall back to the size of a `long` in C in windows
2. Open the csv file with UTF-8 encoding explicitly (instead of relying on locale default)
3. Delete invisible characters at the beginning of `sample.h2k`
ping @pcraig3 and @vadjr to let you know I believe this resolves all the currently known incompatibilities with Windows and Unix.

Windows compatibility changes

---

api/src/schema/enums.js
api/src/schema/index.js
api/src/schema/resolvers.js
api/test/enum.test.js

This allows users to filter results based on values on floor type.
Additionally, the tests have been rethought and refactored so they can just be generated.

Add floor fields to filter field enum

---

api/src/schema/resolvers.js
api/test/queries.test.js

This regex is responsible for converting strings containing numbers into
actual numbers so that values passed to mongo will have the correct
type. As the number of types you can search by expand, it turns out that
this regex doesn't handle integers. This changes that.

Fix regex to handle integers and floats

---

extract_endpoint/src/extract_endpoint/azure_utils.py
extract_endpoint/tests/test_azure_utils.py

This way we'll just have one clearly labelled copy of the emulator values in the code base.

Identify emulator values as such, clean up names

---

etl/src/energuide/dwelling.py
etl/src/energuide/embedded/basement.py
etl/tests/test_dwelling.py

This PR addresses an issue that I noticed regarding how foundation parsing should deal with missing elements.
Report Generator always generates floor rows, even if floor tag is missing, whereas the lack of walls and headers will result in no rows. This PR now emulates that behavior

Always generate floors

---

api/src/schema/enums.js
api/src/schema/index.js
api/src/schema/resolvers.js
api/test/enum.test.js

As advertised. Adding enum functions for heatedFloorArea so that users can filter results based on these fields.

Add enum functions for heatedFloorArea

---

.circleci/config.yml

If I'm reading this correctly, we would currently build & deploy even if the ETL, Node, or Extract Endpoint test steps would fail.

require all CI tests to pass before building

---

etl/src/energuide/element.py
etl/src/energuide/exceptions.py
etl/tests/test_element.py

This PR adds a dynamically-typed `get` function to `Element`. `mypy` is able to determine that if you call `result = my_element.get('/path/to/@attribute', int)`, it is supposed to return an `int`.
This should make it possible to simplify some of the exception handling in #249

typed get function for Element

---

api/src/index.js
api/src/schema/index.js
api/src/server.js

Apollo engine caching defaults to the lowest-defined caching setting per query (default is 0). This means that we have to set an explicit caching setting on each of our `type`s if we want a generic caching behaviour. (ie, if we didn't set it on "walls", any query which included walls would never be cached.)
I've set the time to 90 seconds but that's pretty arbitrary.
Evidence of caching can be seen
- when running locally by removing the 'cacheControl' from `strip: ['cacheControl', ... ] [in the Apollo Engine setup](https://github.com/cds-snc/nrcan_api/blob/master/api/src/index.js#L19)
- by logging into Apollo Engine itself, which gives a visual timeline of requests, and shows how many were returned from the cache
'stores' config was [pinched from the Request Caching …

Add Apollo Engine request caching

---

etl/src/energuide/element.py
etl/src/energuide/embedded/ceiling.py
etl/src/energuide/embedded/code.py
etl/src/energuide/embedded/door.py
etl/src/energuide/embedded/floor.py
etl/src/energuide/embedded/wall.py
etl/src/energuide/embedded/water_heating.py
etl/src/energuide/embedded/window.py
etl/tests/test_element.py

Further to my comment in #260, this PR changes the `assert` call in `element#get_text` to instead raise the custom `ElementGetValueError` exception for easier exception handling.

Get text raises custom error

---

etl/requirements.txt

This PR changes the version of cerberus from the current release (1.1), to a fork of the current development version forked into the cds repo so that it remains static.
This is required because the current release of cerberus contains a bug where coercion does not honour the `nullable` option, meaning even if a key is allowed to be `None`, if the coercion throws an exception on it the validation will fail.
This is fixed in the development (and thus the cds fork) version.

Use cerberus development version

---

extract_endpoint/src/extract_endpoint/azure_utils.py
extract_endpoint/tests/test_azure_utils.py

Add utility functions to upload and download strings to/from Azure. Will be used by the Endpoint to save and retrieve timestamps.

Add Azure utils for string upload / download

---

extract_endpoint/src/extract_endpoint/azure_utils.py
extract_endpoint/src/extract_endpoint/endpoint.py
extract_endpoint/tests/test_azure_utils.py
extract_endpoint/tests/test_endpoint.py

Let the endpoint accept an optional timestamp along with the file. This timestamp is written to its own file in Azure.

Add timestamp to endpoint

---

etl/src/energuide/dwelling.py
etl/tests/test_dwelling.py

This PR adds the add the file_id field to evaluations, this is needed so that home owners can request information on their evaluation
ping @pcraig3

Add file_id to Evaluations

---

api/src/__tests__/i18n.test.js
api/src/schema/Header.js
api/src/schema/__tests__/Header.test.js
api/src/schema/__tests__/schema.test.js
api/src/schema/index.js
api/src/schema/resolvers.js
api/src/schema/types/I18NBoolean.js
api/src/schema/types/I18NFloat.js
api/src/schema/types/I18NInt.js
api/src/schema/types/I18NString.js

This commit is the beginning of the process of splitting this schema up
into smaller pieces. The Header type (needed for foundations) is
included here as it's the type that touched off this little refactoring
operation, but it's not used or visible anywhere.

Start modularizing the schema

---

api/src/schema/index.js

From issue [#4](https://github.com/apollographql/apollo-cache-control-js/issues/4) in the github repo:
> If you don't see cache hits, that usually means there is a path in your response that has maxAge: 0 set. That happens for all objects that do not have an explicit @cacheControl defined, because caching is opt-in.
[Source](https://github.com/apollographql/apollo-cache-control-js/issues/4#issuecomment-341215307)

Cache control tags for types that didn't have them

---

api/src/schema/index.js
api/src/schema/resolvers.js
api/src/server.js
api/test/queries.test.js

Add a `previous` input parameter to allow paging backwards through our results.
Up until this point, we were able to get the next page of results but could never return to the previous page(s).
Also, if both `next` and `previous` are passed in, we throw an error because this a nonsensical thing to do. For more details see commit message.

Add backwards paging to the API results

---

api/src/schema/types/FoundationWall.js
api/src/schema/types/__tests__/FoundationWall.test.js

This type, like the Header before it is used by the soon-to-be-created
Foundation type. It's not in active use anywhere yet.

Add FoundationWall type

---

extract_endpoint/src/extract_endpoint/endpoint.py
extract_endpoint/src/extract_endpoint/post_to_endpoint.py
extract_endpoint/tests/test_endpoint.py
extract_endpoint/tests/test_post_to_endpoint.py

This PR intends to add timestamp as a click option with the default being datetime.now(), which is then passed to post_stream and ultimately the end point to upload a timestamp.txt file with the passed timestamp.
Opinions please!

Add timestamp to post endpoint

---

.circleci/config.yml

This PR changes the name of the job to run in the `node_and+python` workflow from `deploy` to `deploy_api`, what it was renamed to in https://github.com/cds-snc/nrcan_api/pull/266

Rename workflow job

---

etl/src/energuide/embedded/code.py
etl/src/energuide/embedded/wall.py
etl/src/energuide/embedded/window.py
etl/tests/embedded/test_code.py
etl/tests/embedded/test_wall.py
etl/tests/embedded/test_window.py
etl/tests/test_dwelling.py

This PR changes the various information tags in Window and Wall codes to be optional (as it seems from our recent data dump that any of them can be missing).
This change also prompted a general refactor of window and wall codes to make it easier to serialize `Window` and `Wall` objects in their `to_dict` methods to not need to do an explicit check each tag type, getting the english and french text if it exists and using `None` if not.

Refactor codes

---

etl/src/energuide/embedded/heating.py
etl/tests/embedded/test_heating.py

This PR adds 2 new entries to the `_ENERGY_SOURCE_CODES` dictionary now that we have data that has revealed which code goes to which energy source.

New heating source codes

---

etl/src/energuide/embedded/heating.py
etl/tests/embedded/test_heating.py

This PR adds a check to `heating` to accept `btu/h` as a valid unit.
Logs have shown that both are present in the data.

Accept btu/h unit

---

.gitignore
extract_endpoint/Makefile

This PR adds a Makefile to simplify installing & running the mac compatible Azure emulator Azurite for running tests. This Makefile borrows from the ETL Makefile and adds the following:
* a setup_project command that runs the setup_python step & installs azurite globally via NPM
* a start_azurite command that should be used in a separate terminal window to start the emulator
* a is_azurite_running command that is added to the test_python command. This checks to see if Azurite is running before starting the python tests and exits the script if it isn't
I played with running Azurite as a background process, but I think having it as a process in a separate window makes the most sense. There may be times having the output from the emulator will be useful for debugging issues. 
To do: create a …

Makefile for easy installation & running of azurite for tests

---

etl/tests/test_extractor.py

This PR burns some further tech debt by properly naming test fixtures, streamlining the tests, refactoring duplicate code, etc.

simplify extractor tests

---

api/src/schema/resolvers.js
etl/src/energuide/dwelling.py

This PR fixes the typo in the serialization of evaluation of `energyUgrades` to `energyUpgrades`

Fix Mike's typo

---

etl/src/energuide/dwelling.py
etl/src/energuide/extractor.py
etl/src/energuide/snippets.py
etl/tests/randomized_energuide_data.csv
etl/tests/test_dwelling.py
etl/tests/test_extractor.py
etl/tests/test_snippets.py

This PR moves the extraction of forward sortation area and ErsRating from CSV fields to fields extracted directly from the XML. This is not necessarily a good long-term change, but it does bring the extractor in line with the format of the data that we have. i.e. no Postal code or ERSRating field in the CSV.
This is really to unblock our progress at this end for now, it can be moved back at a later date.

Extract "other data"

---

etl/tests/conftest.py
etl/tests/test_azure_skip.py

This PR creates a fixture that attempts to check whether or not the Azure emulator Azurite is running. The fixture checks for the following:
* If the CIRCLECI environment variable exists, run the tests
* If it doesn't exist, try binding to the port Azurite uses (10000)
* If a port error is received (in use), assume it is Azurite & try to run the tests
* If no port error, skip the tests
To use the fixture, add @pytest.mark.usefixtures('is_azurite_running') before any test that requires the Azure emulator

Add pytest fixture and example test

---

api/src/schema/enums.js
api/src/schema/index.js
api/src/schema/resolvers.js
api/test/enum.test.js
api/test/queries.test.js

This change allows users to query for data based on the top level fields
of the foundation type.

Add enum functions for foundation type

---

etl/src/energuide/reader.py
etl/tests/conftest.py
etl/tests/test_cli.py
etl/tests/test_reader.py
etl/tests/test_transform.py

This PR refactors the Azure test skip logic by moving the `pytest.skip` logic inside the same fixture that is used for a populated Azure container. Now tests just ask for the Azure fixture, and if it isn't installed the test automatically skips. Tested locally (skips correctly) and on CI (runs correctly).
Some other minor changes in support of this, specifically moving reading the Azure config inside the function that needs it to enable the test to mock the environment variables.

simplify azure test skips

---

api/package.json
api/src/schema/enums.js
api/src/schema/index.js
api/src/schema/resolvers.js
api/test/enum.test.js
api/test/queries.test.js
api/yarn.lock

Adds a new input parameter 'dateRange' to the 'dwellings' query.
'dateRange' accepts
- a field name: which date to search on
- a startDate: dates that equal or match this date will be returned
- an endDate: dates that equal or match this date will be returned
A few notes:
- Valid queries include:
- a field and a startDate
- a field and an endDate
- a field, a startDate, and an endDate that comes after the
startDate
- Invalid queries include:
- not submitting a field
- a field, but not submitting a 'startDate' or an 'endDate'
- a field, and submitting a startDate equal to or later than
an endDate
- 'creationDate' and 'modificationDate' are both strings that
include timestamp information, but 'entryDate' is just formatted 
'YYYY-MM-DD'. In practice, the only difference between these
formats …

Add date filtering to evaluation date fields

---

etl/src/energuide/cli.py
etl/src/energuide/transform.py
etl/tests/test_transform.py

This PR :fire: `transform.run` since it just calls `database.load` anyway. The "transform" and "load" functions are now separated nicely which simplifies tests.

:fire: transform.run

---

etl/requirements.txt
etl/src/energuide/cli.py
etl/src/energuide/transform.py
etl/tests/conftest.py
etl/tests/test_cli.py
etl/tests/test_transform.py

This PR cleans up some of the local/Azure switching to use some duck-typing to abstract away the problem of reading extracted rows. That had the benefit of cleaning up tests considerably.

Refactor azure/local reading

---

api/src/__tests__/i18n.test.js
api/src/schema/index.js
api/src/schema/resolvers.js
api/src/schema/types/I18NDate.js

Same as with the default scalar types, we need to have a french-language description for our new `GraphQLDate` field.
Note that this PR doesn't add the french description -- just it adds the possibility to add one.

I18N-ize the Date field description

---

extract_endpoint/tests/test_endpoint.py
extract_endpoint/tests/test_post_to_endpoint.py

Removed timestamp related tests because those are now covered by post_to_endpoint with CLI refactor.
Burned references to azure fixtures in test_endpoint, since none of the tests are hitting (or need to hit) the azure storage.

🔥 azure references in test_endpoint

---

etl/src/energuide/cli.py
etl/src/energuide/transform.py
etl/tests/test_transform.py

This PR addresses some issues I had trying to run the `transform` command on the sample data:
- no progress bar
- very messy/long output being displayed on error messages

add progress bar to transform, clean up output

---

.circleci/config.yml

The PR changes the CI configuration to only deploy_endpoint on master, and only if extact_endpoint job succeeded

Only deploy endpoint from master

---

etl/src/energuide/exceptions.py

This PR changes the behaviour of the `InvalidEmbeddedDataTypeError` exception to call `super().__init__` with no arguments if no message was passed in, mimicking how a default exception would behave if nothing was passed to it.

Empty embedded exception message

---

etl/src/energuide/dwelling.py
etl/tests/test_dwelling.py

This PR changes some fields in the `Dwelling` validation step to nullable, meaning they are allowed to be `None` (as long as the keys themselves still exist).

Make certain dwelling fields nullable

---

etl/src/energuide/extractor.py
etl/src/energuide/snippets.py
etl/tests/test_extractor.py

This PR changes the `_extract_snippets` step of extraction to merge in empty versions of the snippets if the nodes are not present, where as the current code simply does not generate those keys in the output if the node is missing.
The current behaviour results in the extractor producing output that fails input validation of the load portion. This new behaviour should ensure that extract does not produce output that is invalid to load.

Merge null snippets

---

etl/src/energuide/extractor.py
etl/tests/test_extractor.py

This PR adds the EVAL_ID to the json filenames in the zipfile produced by extract so that the json files can be sorted by filename prior to grouping.

EVAL_ID in json filenames

---

etl/src/energuide/embedded/water_heating.py

This PR changes the lookup for the water heater type to be case insensitive to the energy and tank type.

case insensitive water heater and energy type

---

.circleci/config.yml

This PR removes some redundant lines in the circleci config.
1. `deploy_endpoint` was present 3 times.
2. `python_integration` and `node_integration` were both present in requires lists, but `node_integration` requires `python_integration` so having both is redundant.

Remove redundant config lines

---

etl/requirements.txt
etl/src/energuide/flask_app.py
etl/tests/test_flask_app.py

* when TL is triggered, respond immediately to Endpoint, and start running TL in a new thread
* if TL is triggered again before it has finished running, ignore the trigger request (and return a `TOO_MANY_REQUESTS` code

Robustify TL web app

---

etl/src/energuide/dwelling.py
etl/tests/test_dwelling.py

This PR allows 1 length groups of `ParsedDwellingDataRow` as long as they are pre-retrofit

Allow single pre-retrofit evaluations

---

etl/src/energuide/embedded/water_heating.py

This PR makes a change to the wood type energy type names. 
Examples of homes that use wood type heating have shown that the energy type is not `wood space heating (mixed wood, hardwood, soft wood or wood pellets)` but instead each one of the wood types is it's own energy type, that all get the same water heater type name.

Fix wood energy type names

---

api/package.json

Adding `lingui compile` to the build step meant that the server kept restarting itself.
By ignoring the 'src/locale' folder, we can prevent this.

Don't restart server if locale files change

---

etl/src/energuide/embedded/heating.py

This PR is a small refactor of the exception handling in`Heating.from_data`. This way only the lines of code that can throw an `ElementGetValueError` are within the try/except block.

Refactor exception handling in Heating.from_data

---

api/src/__tests__/i18n.test.js
api/src/schema/index.js
api/src/schema/resolvers.js
api/src/schema/types/Foundation.js
api/src/schema/types/FoundationFloor.js
api/src/schema/types/FoundationWall.js
api/src/schema/types/Header.js
api/src/schema/types/__tests__/Foundation.test.js
api/src/schema/types/__tests__/FoundationFloor.test.js
api/src/schema/types/__tests__/FoundationWall.test.js

Changing all of the names of our overwritten types to their default names. This will make it easier for external clients to connect to our API, as having changed the names of all the primitive scalar types is possibly a weird gotcha.
`I18NDate` -> `Date`
`I18NBoolean` -> `Boolean`
`I18NInt` -> `Int`
`I18NString` -> `String`
`I18NFloat` -> `Float`
Also changed the return types of a couple fields in the final commit. @buckley-w-david, do those changes look okay to you?

Remove `I18N` prefix from our scalar types

---

etl/src/energuide/embedded/heating.py
etl/tests/embedded/test_heating.py

This PR introduces some changes to `Heating` to correctly parse Baseboard and ComboHeatDhw heater types.
ComboHeatDhw are parsed just like any other type, but Baseboards are structured differently, and fail the parsing, but are all configured the same way.
This PR also adds some missing energy source codes for different types of wood.

Fix Heating errors

---

etl/src/energuide/logger.py

This PR changes how loggers are configured.
Instead of using `logging.basicConfig`, which configures the root logger, it applies the same configuration to loggers produced by `logger.get_logger`.
This results in our logs not being polluted by logging performed by 3rd party libraries such as the `azure` module

Configure subloggers instead of root logger

---

extract_endpoint/Dockerfile
extract_endpoint/requirements.txt

We were running the flask apps using flask's development web server (ie `App.run()`). It's recommended to use `gunicorn` in production.
I think this should do the trick and have it still work on Azure? The new docker container works on my laptop, at least.

run endpoint with gunicorn

---

etl/Dockerfile
etl/requirements.txt

We were running the flask apps using flask's development web server (ie App.run()). It's recommended to use gunicorn in production.

Use gunicorn to run etl flask app

---

etl/src/energuide/cli.py
etl/src/energuide/database.py
etl/src/energuide/flask_app.py
etl/tests/conftest.py
etl/tests/test_flask_app.py

This PR changes how connection strings for MongoDB are generated, as well as adds a `production` flag to the CLI, indication what method of connection string generation should be used.
`--production` signals that it is an Atlas managed MongoDB instance, while `--local` is for anything else (ostensibly a local db, but not necessarily)

Cleanup connection string generation

---

etl/src/energuide/extractor.py

This PR adds an option to `write_data` that signals to compress the data in the output zip file.

Compress data in zip file

---

extract_endpoint/src/extract_endpoint/endpoint.py
extract_endpoint/tests/test_endpoint.py

If there's an error connecting to or using the TL app,  just return `BAD_GATEWAY`, except the case where TL is processing (`TOO_MANY_REQUESTS`). Log the actual code returned from the TL app.

return better code when TL has problems

---

README.md
etl/README.md
etl/src/energuide/cli.py
etl/tests/test_cli.py

This PR makes some adjustments to the `readme` files of ETL and the root project, as well as some changes to allow clearer introspection of operation of the CLI via adding types and help messages to it's options.
As a result of this 1 test needed to be changed, because once the input file of extract is specified as having to exist, the output empty zip is no longer produced, so the test which relied on it's existing failed.

Tighten up documentation

---

api/docs.md
api/package.json
api/yarn.lock

Since GraphQL can introspect itself (win!!), there are a few libraries that can quickly generate docs for us.
[`graphql-markdown`](https://www.npmjs.com/package/graphql-markdown) generates a markdown file listing the various types that are returned by the API.
😎👉  [how cool is this??](https://github.com/cds-snc/nrcan_api/blob/3f5d716414dc3936630b0a73ad115a929bf2edbd/api/docs.md) 👈 😎 
To generate the docs:
- the API must be running locally
- `yarn docs`
It's possible that the README stuff will get restructured as right now it's very "get the app started" focused, but for now this is a reasonable place for these docs to live.
***
Also, several of our users have asked us for the list of fields we'll be giving them, so once this is in we can link them to it.

Add API field documentation

---

extract_endpoint/src/extract_endpoint/endpoint.py
extract_endpoint/tests/test_endpoint.py
extract_endpoint/tests/test_post_to_endpoint.py

Local post sometimes hangs when doing a big upload to Endpoint, despite Endpoint and TL App working correctly. Solution: have Endpoint return `OK` when it receives and validates the post, and run the Azure upload on a new thread. This is similar to how the TL App works.

do azure upload in a thread

---

.circleci/config.yml
api/test/enum.test.js
api/test/queries.test.js

So last week David reminded me that I did, in fact, sort of know Javascript. So instead of staring at a red 'x' sadly, I decided to take a crack at fixing the node integration tests.
Since we're now using AzureReader in our integration test, the way the files are sorted changes and impacts the resulting test data. Also, now all the test data dwellings are in the same FSA, which caused some issues with tests that narrowed down the results using FSA & made assertions on the narrowed data. This PR fixes these issues. I've also attempted to fix issues of the tests assuming data will be returned in a certain order, which I found wasn't reliable now that everything is bundled up into the same FSA. 
- Update the FSA/House data for some entries
- For pagination, everything is in the same FSA now, …

Fix node integration tests

---

extract_endpoint/README.md
extract_endpoint/src/extract_endpoint/post_to_endpoint.py
extract_endpoint/tests/test_post_to_endpoint.py

user can set an environment variable `ENERGUIDE_ENDPOINT_ADDRESS` to the Endpoint url and then not need the `--url` option to contact Endpoint in Azure.

use endpoint address environment variable

---

nrcan_etl/src/energuide/element.py
nrcan_etl/src/energuide/exceptions.py
nrcan_etl/tests/test_element.py

This PR extracts the next piece of #392 
It adds in the `Element` datatype and the exceptions from `etl`, unchanged from their implementation in `etl`

Add element type for upgrade priorities

---

nrcan_etl/src/energuide/extractor.py
nrcan_etl/tests/test_extractor.py

This PR is the first in the line of #392 changes that makes real changes.
It adds in an extractor similar to the one in `etl`, but with most xml extraction removed, and some additional TSV fields extracted.
This should be all that is needed to be extracted to satisfy the information in the priority data fields.

Add extractor

---

nrcan_etl/tests/conftest.py

This PR adds in a small bit of the conftest in #392, only what is needed for `Dwelling`, which will soon be added.

Add stripped down conftest

---

nrcan_etl/src/energuide/dwelling.py
nrcan_etl/tests/test_dwelling.py

One of the last PRs in the series for #392 
This PR adds in Dwellings, copied from `etl` but with a lot of it removed, and some added.
It is in a stable position, but does not yet incorporate all the priority data fields, but does do schema verification that they are all there.

Add dwellings

---

.circleci/config.yml

Noticed today that at some point the circleci config got slightly broken in such a way that if `python_integtation` fails, we won't get the failure notification.
This PR fixes that error.

Report failing master on python_integration

---

nrcan_etl/src/energuide/dwelling.py

Additional fields were being serialized with snake_case names instead of camelCase.
This PR standardizes them on camel.

fix mixed snake and camel case

---

api/src/schema/__tests__/schema.test.js
api/src/schema/index.js
api/test/queries.test.js

Walls are now modelled differently, so I'm changing the API to return the new data format.
Also added unit tests and an integration test. Should be good to merge. 👍 
***
(this is how walls look now)
```
"walls": {
"measurement": {
"insulation": [
{
"percentage": 45.3,
"rValue": 12.0
},
{
"percentage": 4.7,
"rValue": 12.0
}
],
"heatLost": 27799.9
},
"upgrade": {
"insulation": [
{
"percentage": 45.3,
"rValue": 12.0
},
{
"percentage": 4.7,
"rValue": 12.0
}
],
"heatLost": 27799.9
}
}
```

Add new Wall type to API

---

nrcan_etl/src/energuide/embedded/walls.py
nrcan_etl/tests/embedded/test_walls.py
nrcan_etl/tests/test_dwelling.py

This PR changes the name for heat loss in walls from `heat_lost` to `heat_loss`.

change heat_lost to heat_loss

---

nrcan_etl/src/energuide/dwelling.py

Currently every group of evaluations that is being parsed into `ParsedDwellingDataRow` has it's own instances of `DwellingValidator` being created. 
This is wasteful and unnecessary, and is changed in this PR.

Create only one instance of Validator

---

nrcan_etl/src/energuide/dwelling.py
nrcan_etl/tests/test_database.py

After some thought, a house could change house types between evaluations if massive renovations were done, so house_type is being moved from a dwelling level piece of data to the evaluation level.

Move house_type to Evaluation

---

nrcan_etl/src/energuide/dwelling.py

This PR refactors `_filter_dummy_evaluations` to...
1. Not filter out `F` evaluations
2. Be prettier

Keep F evaluations

---

nrcan_etl/src/energuide/transform.py
nrcan_etl/tests/test_transform.py

This PR adds in the functionality of #351 that seemed to have been missed in the transition from `etl` to `nrcan_etl`

Add Sort localFileReader change from etl that was missed in transfer

---

nrcan_etl/src/energuide/embedded/evaluation_type.py
nrcan_etl/tests/test_dwelling.py

This PR adds some a missing test to ensure that dwellings throw away "dummy" pre-evaluations (defined as pre-evaluations that have the same ENTRYDATE as another post-evaluation)

Test dummy evaluations are filtered out

---

api/src/schema/__tests__/schema.test.js
api/src/schema/index.js
api/test/queries.test.js

This PR adds houseType to Evaluation, which is a string that describes the type of house being evaluated. We decided to add this to Evaluation instead of Dwelling due to the fact that major renovations can lead to a changed house type between evaluations.

Add house type to evaluation

---

api/src/schema/__tests__/schema.test.js
api/src/schema/index.js
api/test/queries.test.js

This PR refactors heatedFloorArea. The new heatedFloorArea is just a Float value in the evaluation.

Add heated floor area to Evaluation

---

Makefile
README.md
nrcan_etl/Makefile

This PR fixes some missing changes to the README referencing the old `etl`, and also changes the makefile(s) to now work with the new `nrcan_etl`

adapt README and Makefile(s) to nrcan_etl

---

resource/add_to_etl.md

This PR adds a step-by-step series of instructions on adding an example element to the ETL process (AIR50P)

Add step by step ETL instructions

---

nrcan_etl/src/energuide/database.py

This PR changes the database loading code to chunk up the documents into bulk replace operations 1000 documents at a time.

bulk update instead of one at a time

---

nrcan_etl/src/energuide/dwelling.py
nrcan_etl/src/energuide/embedded/house_type.py
nrcan_etl/tests/embedded/test_house_type.py
nrcan_etl/tests/test_dwelling.py

This PR adds some data cleaning to the parsing of the TYPEOFHOUSE TSV field to make it more consistent.
Observation of the data yields that all the current values of houseType are:
```
[
"Single detached",
"Detached Duplex",
"Single Detached",
"Row, end unit",
"Row house, end unit",
"Row house, middle unit",
"Double/Semi-detached",
"Mobile home",
"Apartment Row",
"Apartment",
"Attached Triplex",
"Detached Triplex",
"Attached Duplex",
"Mobile Home",
"Double/Semi Detached",
"Triplex (non-MURB)",
"Duplex (non-MURB)",
"Row, middle unit",
"Double/Semi-Detached",
"Apartment (non-MURB)"
]
```
Some of these are obviously the same but different by case, but some (such as "Row, end unit" and "Row house, end unit") seem like they could be the same, but is hard to tell.
We are leaving the cleaning to …

Clean house type

---

api/package.json

This path only works on *nix machines, and isn't required since yarn/npm
assume everything is in your node_modules folder anyway.

Remove *nix-y path from docs command
